name: Deploy to Google Cloud Run

on:
push:
branches:
- main

jobs:
deploy:
name: Build and Deploy to Cloud Run
runs-on: ubuntu-latest

steps:
# 1. Checkout code
- name: Checkout source
uses: actions/checkout@v4

# 2. Authenticate with Google Cloud
- name: Authenticate to Google Cloud
uses: google-github-actions/auth@v2
with:
credentials_json: '${{ secrets.GCP_SA_KEY }}'

# 3. Set up gcloud CLI
- name: Set up Cloud SDK
uses: google-github-actions/setup-gcloud@v2

# 4. Configure Docker to use gcloud as a credential helper
- name: Configure Docker
run: gcloud auth configure-docker

# 5. Build and push Docker image
- name: Build and push Docker image
run: |
docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA .
docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA

# 6. Deploy to Cloud Run
- name: Deploy to Cloud Run
run: |
gcloud run deploy my-app \
--image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA \
--region ${{ secrets.GCP_REGION }} \
--platform managed \
--allow-unauthenticated
